version: '3'

services:
  db:
    build: ./.docker/mysql
    container_name: nestjs-mysql8-container
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    tty: true
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: fin
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - ./.docker/db_data:/var/lib/mysql
  app:
    build: .
    entrypoint: dockerize -wait tcp://db:3306 -timeout 40s ./.docker/entrypoint.sh
    container_name: fullcycle_nestjs_api_mysql
    ports:
      - 3000:3000
    volumes:
      - .:/home/node/app
    depends_on:
      - db
