version: '3.5'

services:
  api:
    container_name: nest_api
    build: .
    ports:
      - ${API_PORT}:${API_PORT}
    volumes:
      - .:/home/api
    environment:
      DB_HOST: db
      DB_PORT: 5432
    depends_on:
      - db

  db:
    container_name: nest_api_db
    image: postgres:13
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - ${DB_PORT}:5432
