GET http://localhost:3000/orders

###

GET http://localhost:3000/orders/002a200c-0e7e-48e6-9ed7-0ad1dba4c45b

###

POST http://localhost:3000/orders
Content-Type: application/json

{
  "amount": 100
}

###

PATCH http://localhost:3000/orders/002a200c-0e7e-48e6-9ed7-0ad1dba4c45b
Content-Type: application/json

{
  "amount": 50
}

###

DELETE http://localhost:3000/orders/002a200c-0e7e-48e6-9ed7-0ad1dba4c45b
